### ISSUE TITLE
Failure to build

### ISSUE THREAD

**Issue by ghost** [prsolucoes/gohc#3]
Is there a particular version of `sendgrid` with which `gohc` _does_ compile?

```
484)~ % go get -u github.com/prsolucoes/gohc
# github.com/prsolucoes/gohc/models/domain
Software/go3rdparty/src/github.com/prsolucoes/gohc/models/domain/notifier_plugin_sendgrid.go:76: undefined: sendgrid.NewSendGridClientWithApiKey
Software/go3rdparty/src/github.com/prsolucoes/gohc/models/domain/notifier_plugin_sendgrid.go:78: undefined: sendgrid.NewMail
485)~ % uname -a
Linux dazservs01.hotsos.space 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
486)~ % go version
go version go1.6.3 linux/amd64
```

**Comment by ghost** [comment]
To answer my own question, for others encountering this problem: poking around in `sendgrid`'s history shows that revision `d88aa4dd8b2a9df3a9693d35d4d0f686b3bcff9a` gets `gohc` to compile.

FYI, the way I got this to finally compile was to vendor manage the dependency to the revision; in my case, I used [gvt](https://github.com/FiloSottile/gvt):

```
cd github.com/prsolucoes/gohc
gvt fetch -revision d88aa4dd8b2a9df3a9693d35d4d0f686b3bcff9a github.com/sendgrid/sendgrid-go
go get github.com/prsolucoes/gohc
```

**Comment by paulocoutinhox** [comment]
Hi,
Thanks for report it. I upgrade the library here and update the code too.
I will put it on vendor in future.

You can update will new code using:

> go get -u github.com/sendgrid/sendgrid-go
> go get -u github.com/prsolucoes/gohc
> go install github.com/prsolucoes/gohc

Thanks.
